comment: false

coverage:
  ignore:
    - "R/utils-optional-dependencies.R"
    - "R/zzz.R"
    - "R/utils-ui.R"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
