#!/usr/bin/env Rscript
# Build CRAN-style PDF and HTML reference manuals for DeCovarT.
#
# Usage (repository root):
#   Rscript scripts/generate_package_manual.R
#
# Outputs:
#   output/manual/DeCovarT.pdf   — via tools::texi2pdf / R CMD Rd2pdf
#   output/manual/html/          — per-topic HTML via tools::Rd2HTML
#   output/manual/index.html     — simple index of exported topics

root <- normalizePath(".", winslash = "/", mustWork = TRUE)
out_dir <- file.path(root, "output", "manual")
html_dir <- file.path(out_dir, "html")
dir.create(html_dir, recursive = TRUE, showWarnings = FALSE)

man_dir <- file.path(root, "man")
rd_files <- list.files(man_dir, pattern = "\\.Rd$", full.names = TRUE)
if (!length(rd_files)) {
  stop("No Rd files found under man/; run devtools::document() first.")
}

# --- PDF (same pathway as devtools::build_manual / R CMD Rd2pdf) ------------
pdf_path <- file.path(out_dir, "DeCovarT.pdf")
pkg_dir <- root
message("Building PDF manual → ", pdf_path)
status <- system2(
  file.path(R.home("bin"), "R"),
  args = c(
    "CMD",
    "Rd2pdf",
    "--batch",
    "--no-preview",
    "--force",
    paste0("--output=", pdf_path),
    pkg_dir
  ),
  stdout = TRUE,
  stderr = TRUE
)
writeLines(status, file.path(out_dir, "Rd2pdf.log"))
if (!file.exists(pdf_path)) {
  warning(
    "PDF manual was not produced. See output/manual/Rd2pdf.log. ",
    "Ensure a TeX engine is installed (e.g. latexmk / texlive)."
  )
} else {
  message("PDF OK (", round(file.info(pdf_path)$size / 1024), " KiB)")
}

# --- HTML (one page per Rd topic + index) ----------------------------------
message("Building HTML topics → ", html_dir)
topics <- character()
for (rd in rd_files) {
  topic <- sub("\\.Rd$", "", basename(rd))
  dest <- file.path(html_dir, paste0(topic, ".html"))
  ok <- tryCatch(
    {
      tools::Rd2HTML(rd, out = dest, package = "DeCovarT")
      TRUE
    },
    error = function(e) {
      message("Skipping ", topic, ": ", conditionMessage(e))
      FALSE
    }
  )
  if (isTRUE(ok) && file.exists(dest)) {
    topics <- c(topics, topic)
  }
}

topics <- sort(unique(topics))
index_lines <- c(
  "<!DOCTYPE html>",
  "<html lang=\"en-GB\">",
  "<head>",
  "  <meta charset=\"utf-8\">",
  "  <title>DeCovarT function reference</title>",
  "  <style>",
  "    body { font-family: system-ui, sans-serif; margin: 2rem; }",
  "    li { margin: 0.25rem 0; }",
  "  </style>",
  "</head>",
  "<body>",
  "  <h1>DeCovarT function reference</h1>",
  "  <p>Generated by <code>scripts/generate_package_manual.R</code>. ",
  "For the interactive site see ",
  "<a href=\"https://bastienchassagnol.github.io/DeCovarT/reference/\">",
  "pkgdown reference</a>.</p>",
  if (file.exists(pdf_path)) {
    "  <p><a href=\"DeCovarT.pdf\">Download PDF manual</a></p>"
  } else {
    "  <p><em>PDF manual not available in this build.</em></p>"
  },
  "  <ul>",
  paste0(
    "    <li><a href=\"html/",
    topics,
    ".html\">",
    topics,
    "</a></li>"
  ),
  "  </ul>",
  "</body>",
  "</html>"
)
writeLines(index_lines, file.path(out_dir, "index.html"))
message(
  "Wrote ",
  file.path(out_dir, "index.html"),
  " (",
  length(topics),
  " topics)"
)
message("Done.")
